

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datacollect?serverTimezone=GMT%2B8
    username: root
    password: LOLlol01
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
mybatis:
  type-aliases-package: com.lbl.forumbackend.pojo
  mapper-locations:
    - classpath:mapper/*.xml
  config-location:
    - classpath:config/mybatis-config.xml
server:
  port: 8086